"""add_printer_model

Revision ID: cfddc39e63ff
Revises: 5727d5c5d61c
Create Date: 2026-02-20 19:28:43.461792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'cfddc39e63ff'
down_revision: Union[str, Sequence[str], None] = '5727d5c5d61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('snmp_community', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('toner_black', sa.Integer(), nullable=True),
    sa.Column('toner_cyan', sa.Integer(), nullable=True),
    sa.Column('toner_magenta', sa.Integer(), nullable=True),
    sa.Column('toner_yellow', sa.Integer(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printer_ip_address'), 'printer', ['ip_address'], unique=True)
    op.create_index(op.f('ix_printer_store_name'), 'printer', ['store_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_printer_store_name'), table_name='printer')
    op.drop_index(op.f('ix_printer_ip_address'), table_name='printer')
    op.drop_table('printer')
    # ### end Alembic commands ###
