"""verify_models

Revision ID: fba776f80d0f
Revises: e7f8a9b0c1d2
Create Date: 2026-03-10 09:30:27.583312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fba776f80d0f'
down_revision: Union[str, Sequence[str], None] = 'e7f8a9b0c1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('mediaplayer_ip_address_key'), 'mediaplayer', type_='unique')
    op.drop_index(op.f('ix_mediaplayer_ip_address'), table_name='mediaplayer')
    op.create_index(op.f('ix_mediaplayer_ip_address'), 'mediaplayer', ['ip_address'], unique=True)
    op.create_index(op.f('ix_printer_ip_address'), 'printer', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_printer_ip_address'), table_name='printer')
    op.drop_index(op.f('ix_mediaplayer_ip_address'), table_name='mediaplayer')
    op.create_index(op.f('ix_mediaplayer_ip_address'), 'mediaplayer', ['ip_address'], unique=False)
    op.create_unique_constraint(op.f('mediaplayer_ip_address_key'), 'mediaplayer', ['ip_address'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
